replicaCount: 1

image:
  repository: sonatype/nexus3
  tag: latest # Replace with the desired version
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

ingress:
  enabled: true
  host: nexus.example.com
  annotations: {}
  tls: []

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1"

nexus:
  contextPath: /
  javaOpts: "-Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
