apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-oss
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nexus-oss
  template:
    metadata:
      labels:
        app: nexus-oss
    spec:
      containers:
      - name: nexus-oss
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8081
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc
