apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-oss.fullname" . }}
  labels:
    app: {{ include "nexus-oss.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nexus-oss.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nexus-oss.name" . }}
    spec:
      containers:
        - name: nexus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: NEXUS_CONTEXT
              value: "{{ .Values.nexus.contextPath }}"
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "{{ .Values.nexus.javaOpts }}"
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: {{ include "nexus-oss.fullname" . }}-pvc
