{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nexus-oss.fullname" . }}-pv
  labels:
    app: {{ include "nexus-oss.name" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: /data/nexus
{{- end }}
